sudo: false
language: node_js
node_js:
- '4'
- '6'
- '8'
- '10'
- '12'
- '13'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: VeOUG+hvMn5Hw/irdFSPohE64OZ7oeY5d9HhePJHuHtHY9ubFJC3FfFyKJK3dlihO9eir+T37WT1zUk2zcWH/5GhYTvQn5L/vFSJllZzFeKF8Vr5/mPyFREviF54R4URyBA/XP3j1owsYfQ8WXMy+355/MC6Az+Jkb3LSKxWRKsY61LSYzaGPkEV+fKnFn85YZmLTSm+j3Kg8DTIAX3UCAqHeDeErND4JckIPCb6xbcE+leWi3JvVvrFuw8XBwne3wszJJnaFaRBoRQjdS5SDRo65WAOzlha3N4Vj0jsgdekN+TabuttmdtcnivKscVKKh+wg9BlKFkugBRdKbzf9tJrfvN8V6Q6e6bdrvepns3gdpZ9x0ji1GWoKRQm4jJG4Oyf3TNZXs/66nbY3dOjnoqS4omiSHVytPY7GU3evj33bWnQ09jCfqXo1+URnMQiPBZUeWKQyl4XUsDYSOLzFrjlokP7oWccCt1m+5YmtXOQc+caXlk7LvRyNBQ03MRfSWGD0Ko9oy4xVQ0QZo+Fb4Bzl5LIKKkf1p7WgSG0t0xRd2ZIjnp7XEsQOGTMWF2HWXU9cuoD3RAJlTh1OlurClXY7H7PPLHwi8eRmRcDx+pSs3xfY8vuEZGxlRbq+j+Mlppjt8ZYPcPgXOg0l8bwOyTjixUBrRb3BbEPVeAnMV4=
