version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      GkRTrX58Tu2fW3NmStpcm+GC2+G3FZBLkdQ0UfS4LcCQNG0bwbj+l4W4RSDvkFpFRuoY3EXbxA1aEcd+DjOHHshQnWDlYNfX62PwrAqCnON9JrDwAP9XrBAWpTTswkzu/MO52m7YR0Sp1CQzwHqV4bQNbW/SmffXUIRcSodwMUBM+rd3EfRyjXEWtsfxOmT9VqxcDVA5czTFAWHz8e0Cox6TUi986o/s3z9BMyh/EofT3RUWoZrII5rRu0i2SJCftx3R3JMM0Q1SATS44rK/p/y/b1873bmSoCKpqYNDze6SAODFtZBZpTmVqFpDR/Wp6lYM+n++is/4ovWVHd26hTUmWLYbNe74K4X+2JlIJmc1JJmLPYiH15Q6XlmrDoOaHw4jkPDNsp5t/Z0xo6upYZz4soVUobtDBSeDtwXCqXGjLe15PPOLSBBPhIHNTPPsX2H8+l/Ue701PYVlO8SGM5VAHisUVMnZkH/s4wrz4mx4ffpN8YK0/1oxe0OM31geKiWrtK1LSJupWKyRzXe7Cy75OdUSmxSkIxh3gUjz7T1mwg6c4qpC2PhxYoJSYVnmKfj6N+jKrdl16fvNjwxDQMOsIuDaf/9phqr3RKrUrHmAQ9Cls93Au2fGN9XpslO8ucKC4DtER1z6BSc2zjWOH7csigIEunjl+XJKpwvuGJs=
