version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      djufAndcNx9Vu0qFoxDYIinTSa4CC/KD0JpGWLV62l4kpJFOftOINI4PJhCm97AlXXpwIkrZ9F+SxXYYj++V+PXH4k7BsHVRFDVFYiLWrVd/etMjpRRfNuaznzOpV3YRXnqGKoAgudDc1Xsc1Q/71vsw+v6++Ao7lSFu0zm+C3kaVPx+zdMdz9LDYErbvdYEL6b4OHJ+5dv7GnSyqfH0SgGMnNfJdO7NBaPnDJYKnsC2fDIHirQtKjjyRogGRtcJPFPwgT0eG7/iSQP9FDoLAmiZ/tGd79QPA6KZmqDOtWKp05Olq+UljOiC+aJUBK0D3NR4/NeRj73TdsrXlpxpUy4ZSRe3h8Hoh7ghGVJK2l4oXO0JxRj0aWzjhor/9O3kD7cUL5Gkm7lT4McltrKTQwLf2f5iAuI+Q9xXa1LGtpb2ffj2LYbq1ShljIGuFETdIUwFWwiMqjWxM2yZ51WrmTtgpqVkzwg3Cbj8oYp6p0H4WkqMKQ4sosz6D8cx14sLWNrYtZLF55tDfvuuG6sV8lMkKNiAzRZSMGtNGcPjf0uheh3/5hJnqhGF1Q6gEALSaA/+v74zyH3QjOUfTFrbMp/7qkwutHSYVTRhq+z1FH/CB82A83085CBbIS/MIUhHog3issaLK/Ws1oXily4mrPs6ZSukpRufLuDiFnGdC0I=
