version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      odk8bcIMKN1JRt/h1XO5o+wLtED5ry3ghLRK1JWPIBOF5ZnjOMFhg4QdXr1481TnJUzFIqUe/JSR8GyZsQbosA1Mzu8XBrD7PL1QgXdbPBZvRisCri1M7v32hJc4HnNeVM8LojLOeph/RucvWvRuKsOs/G9uWP7Zv18loqXsz96aV5Yqb18DmqNRtljnleD9CRXrpOxIG000TtbMrNZPHGayrGI2fS5+6nLSmC9JZdmCnPrMN1HQLRCRIpG7ircXIoH1O1IakYPE3EzJvijOQc3sz4lUl73VO4qX/+2CZaXmcOZZvaRKtulB29B5s6i+i0SegX1RZ+ZbB+EzG6ljv7upGboplBwHGQC8UnS7xKV6eAaq0zUtJYlPfZDu11pK3TSoA87uDFI6lyIIySp6wmcVCb1y9AGndgOzus4U/PCFkP8rzd/TqabTu1mPlNJrMmAM36IyctaCPGsDO5ZbjCyqS5nMBlIc1CUAbWUQBTCKqv4t3/pd2mE2RUKqkXgHTQI9lGANU0YrGiCtRHh2TZsGF1khFzQ1phK2pDi0yKCkGN2PpE9e1DU/PyDiXtxOobed4WTuQbOpVKsPrT7BUyQnaxa/+/Ba6P15jOcQ+B3VPNru+re2eTtoQnxRmtqJVNzA1XZN5kY7UIZ2bwF0Th11VcoPe6/kx5lz1NB493k=
