version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      jhSjGNiLEcOC18szkCMzbI3/AZSrHkVMMUATxm8PvaMBZFk/b308wS9Vfos+cq0Jz7C5bWlAgHKc695Hsl/ZJGjcWPGgq2jqWAzwglyyo2cBBwe4k2ZROhC/rBR6Nolxa/tH/LJfJODzKc7hQkcczZ41inByrkg9Xn2d9LjbLqgpCYO4P6x8/zz3Js1qUHOxJYUzKVjHMfD6G5KPQrDVyw4+cUKXd19+1P/PkmaPZI3KgQdjyx12kB09+NuraHYR5TdGE479s300gSSO5MIC4+GwiYx5LXOWhYnSjMCPzb0exuG/q9bTRN1JhctypWZF5jFkMdW6phUsI2Weqen0eWmCiOCeEvSPyMZiTPfnX4B0T3pqybF1wk9oGr11gFr+sQgCdj9hrMKA7BiBG1/3g7gbryZbc0JhEgaZG+QpABNy8EmMzVfohd7Mgl/wbk2fy2W+AiJ5R9DDYbw60M36MmzeVPfnW5tr0CrNepfqMsOZ9zQehJxPoGR77RaF8/kI7xgIRRgtlen5Q4OVdqhVZJsrRfflMfu6r+zKAz/oHkQwAZ0vvzZI1PipaCEMoJwsuM4ikL8dvrQZoKlQAP6ictFqjLDJo3kPIdncwlATjA33kgfeRLOV5LSZ+7FxP1j6XtxBfVnyV4VyBiOlXiCh7rAnfaEqHQfza6pfKzytS9g=
